language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t snowdej/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true snowdej/docker-react npm run test

    
