version: '3'
services:
    frontend:
        stdin_open: true
        tty: true
        environment:
            # only for windows docker hosts or file changes are ignored
            - CHOKIDAR_USEPOLLING=true
        build: 
            context: .
            dockerfile: Dockerfile.dev    
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
        image: frontend